/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Has_A.FamilyMember;
import Is_A.Business;
import Is_A.Ticket;
import Main_Sys.TicketSys;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Sumeyye
 */
public class AddTicketFrame extends javax.swing.JFrame {

    SpecialServicesFrame ssf = new SpecialServicesFrame();
    SearchTicket st = new SearchTicket(this);

    /**
     * Creates new form AddTicketFrame
     */
    public AddTicketFrame() {
        initComponents();
        setTitle("Buy Ticket Page");
        setLocationRelativeTo(null);
        setSize(1300, 700);

        if (economyBTN.isSelected()) {
            economyPNL.setVisible(true);
            businessPNL.setVisible(false);
        } else if (businessBTN.isSelected()) {
            economyPNL.setVisible(false);
            businessPNL.setVisible(true);
        }

    }

    public void fillCB() {
        st.SearchUserNameCMB().setModel(new DefaultComboBoxModel(TicketSys.getUserNames()));
        st.RemoveUserNameCMB().setModel(new DefaultComboBoxModel(TicketSys.getUserNames()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        classBG = new javax.swing.ButtonGroup();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        economyBTN = new javax.swing.JRadioButton();
        businessBTN = new javax.swing.JRadioButton();
        manageClassesPNL = new javax.swing.JPanel();
        economyPNL = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        seatTypeCMB = new javax.swing.JComboBox<>();
        purchaseMealCB = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        luggageTF = new javax.swing.JTextField();
        businessPNL = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        movieTF = new javax.swing.JTextField();
        bookTF = new javax.swing.JTextField();
        foodTF = new javax.swing.JTextField();
        drinkTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        luggage_bTF = new javax.swing.JTextField();
        addSpecialServices = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fromTF = new javax.swing.JTextField();
        toTF = new javax.swing.JTextField();
        depDayTF = new javax.swing.JTextField();
        depTimeTF = new javax.swing.JTextField();
        phoneTF = new javax.swing.JTextField();
        nameTF = new javax.swing.JTextField();
        surnameTF = new javax.swing.JTextField();
        ageTF = new javax.swing.JTextField();
        usernameTF = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        famNameTF = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        famSurnameTF = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        famAgeTF = new javax.swing.JTextField();
        addFamMemberBTN = new javax.swing.JButton();
        clearBTN = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        buyBTN = new javax.swing.JButton();
        clearAllBTN = new javax.swing.JButton();
        displayBTN = new javax.swing.JButton();
        search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dispTA = new javax.swing.JTextArea();
        messageLBL = new javax.swing.JLabel();
        ticketInfoPNL = new javax.swing.JPanel();

        jLabel20.setText("jLabel20");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("From:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 60, 20));

        classBG.add(economyBTN);
        economyBTN.setSelected(true);
        economyBTN.setText("Economy Class");
        economyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                economyBTNActionPerformed(evt);
            }
        });
        getContentPane().add(economyBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        classBG.add(businessBTN);
        businessBTN.setText("Business Class");
        businessBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                businessBTNActionPerformed(evt);
            }
        });
        getContentPane().add(businessBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        manageClassesPNL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        economyPNL.setBorder(javax.swing.BorderFactory.createTitledBorder("Economy Class"));
        economyPNL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Seat Type:");
        economyPNL.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 34, -1, -1));

        seatTypeCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Window", "Middle", "Passage" }));
        economyPNL.add(seatTypeCMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 31, -1, -1));

        purchaseMealCB.setText("Purchase Meal");
        economyPNL.add(purchaseMealCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 71, 140, -1));

        jLabel3.setText("Luggage: ");
        economyPNL.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 117, -1, -1));
        economyPNL.add(luggageTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 114, 64, -1));

        manageClassesPNL.add(economyPNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 150));

        businessPNL.setBorder(javax.swing.BorderFactory.createTitledBorder("Business Class"));
        businessPNL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Movie:");
        businessPNL.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 34, -1, -1));

        jLabel5.setText("Book:");
        businessPNL.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 74, -1, -1));

        jLabel6.setText("Food:");
        businessPNL.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 114, -1, -1));

        jLabel7.setText("Drink:");
        businessPNL.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 149, -1, -1));
        businessPNL.add(movieTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 31, 101, -1));
        businessPNL.add(bookTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 71, 101, -1));
        businessPNL.add(foodTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 111, 100, -1));
        businessPNL.add(drinkTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 146, 99, -1));

        jLabel8.setText("Luggage: ");
        businessPNL.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 189, -1, -1));
        businessPNL.add(luggage_bTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 186, 44, -1));

        addSpecialServices.setText("Add Special Services After Flight");
        addSpecialServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSpecialServicesActionPerformed(evt);
            }
        });
        businessPNL.add(addSpecialServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 30));

        jLabel21.setText("Warnning: In order to add Special Services ");
        businessPNL.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 340, 30));

        jLabel22.setText("you must buy the ticket.");
        businessPNL.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        manageClassesPNL.add(businessPNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 290, 330));

        getContentPane().add(manageClassesPNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 290, 360));

        jLabel9.setText("To:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel10.setText("Departure Day:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel11.setText("Departure Time: ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel12.setText("Name:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jLabel13.setText("Surname:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        jLabel14.setText("Age:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        jLabel15.setText("Username:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        jLabel16.setText("Phone Number:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));
        getContentPane().add(fromTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 100, -1));
        getContentPane().add(toTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 100, -1));
        getContentPane().add(depDayTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 60, -1));

        depTimeTF.setToolTipText("");
        getContentPane().add(depTimeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 60, -1));
        getContentPane().add(phoneTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 150, -1));
        getContentPane().add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 120, -1));
        getContentPane().add(surnameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 120, -1));
        getContentPane().add(ageTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 50, -1));
        getContentPane().add(usernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 120, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Family Member"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("Name: ");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        jPanel1.add(famNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 130, -1));

        jLabel18.setText("Surname:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        jPanel1.add(famSurnameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 130, -1));

        jLabel19.setText("Age:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        jPanel1.add(famAgeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 60, -1));

        addFamMemberBTN.setText("Add Family Member");
        addFamMemberBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFamMemberBTNActionPerformed(evt);
            }
        });
        jPanel1.add(addFamMemberBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        clearBTN.setText("Clear");
        clearBTN.setToolTipText("");
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });
        jPanel1.add(clearBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        jLabel23.setText("In order to add your family members, you must buy your own ticket first.");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 440, 210));

        buyBTN.setText("Buy Ticket");
        buyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyBTNActionPerformed(evt);
            }
        });
        getContentPane().add(buyBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, -1, -1));

        clearAllBTN.setText("Clear");
        clearAllBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllBTNActionPerformed(evt);
            }
        });
        getContentPane().add(clearAllBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, 80, -1));

        displayBTN.setText("Display");
        displayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBTNActionPerformed(evt);
            }
        });
        getContentPane().add(displayBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, -1, -1));

        search.setText("Search/Remove Ticket");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, -1, -1));

        dispTA.setEditable(false);
        dispTA.setColumns(20);
        dispTA.setRows(5);
        jScrollPane1.setViewportView(dispTA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 340, 530));

        messageLBL.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(messageLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, 490, 40));

        ticketInfoPNL.setBorder(javax.swing.BorderFactory.createTitledBorder("Ticket Information"));
        ticketInfoPNL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(ticketInfoPNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 580, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void economyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_economyBTNActionPerformed
        // TODO add your handling code here:
        economyPNL.setVisible(true);
        businessPNL.setVisible(false);
    }//GEN-LAST:event_economyBTNActionPerformed

    private void businessBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_businessBTNActionPerformed
        // TODO add your handling code here:
        economyPNL.setVisible(false);
        businessPNL.setVisible(true);
    }//GEN-LAST:event_businessBTNActionPerformed

    private void addSpecialServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSpecialServicesActionPerformed
        // TODO add your handling code here:
        ssf.setVisible(true);
    }//GEN-LAST:event_addSpecialServicesActionPerformed

    private void buyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyBTNActionPerformed
        // TODO add your handling code here:

        if (economyBTN.isSelected()) {

            if (fromTF.getText().isEmpty() || toTF.getText().isEmpty()
                    || depDayTF.getText().isEmpty() || depTimeTF.getText().isEmpty()
                    || nameTF.getText().isEmpty() || surnameTF.getText().isEmpty()
                    || ageTF.getText().isEmpty() || usernameTF.getText().isEmpty()
                    || phoneTF.getText().isEmpty() || luggageTF.getText().isEmpty()) {
                messageLBL.setText("Please fill the blanks.");
            } else {
                boolean res = TicketSys.addEconomy(fromTF.getText(), toTF.getText(),
                        depDayTF.getText(), depTimeTF.getText(),
                        nameTF.getText(), surnameTF.getText(),
                        ageTF.getText(), usernameTF.getText(), phoneTF.getText(), (String) seatTypeCMB.getSelectedItem(),
                        purchaseMealCB.isSelected(), luggageTF.getText());

                if (res) {
                    messageLBL.setText("Ticket is bought.");
                } else {
                    messageLBL.setText("Ticket is already bought");
                }
                TicketSys.calcAllFees();

            }

        } else if (businessBTN.isSelected()) {

            if (fromTF.getText().isEmpty() || toTF.getText().isEmpty()
                    || depDayTF.getText().isEmpty() || depTimeTF.getText().isEmpty()
                    || nameTF.getText().isEmpty() || surnameTF.getText().isEmpty()
                    || ageTF.getText().isEmpty() || usernameTF.getText().isEmpty()
                    || phoneTF.getText().isEmpty() || luggage_bTF.getText().isEmpty() || movieTF.getText().isEmpty()
                    || bookTF.getText().isEmpty()
                    || foodTF.getText().isEmpty()
                    || drinkTF.getText().isEmpty()) {
                messageLBL.setText("Please fill the blanks.");
            } else {

                boolean res = TicketSys.addBusiness(fromTF.getText(), toTF.getText(),
                        depDayTF.getText(), depTimeTF.getText(),
                        nameTF.getText(), surnameTF.getText(),
                        ageTF.getText(), usernameTF.getText(), phoneTF.getText(),
                        movieTF.getText(),
                        bookTF.getText(),
                        foodTF.getText(),
                        drinkTF.getText(),
                        luggage_bTF.getText());

                if (res) {
                    messageLBL.setText("Ticket is bought. You may add special services after flight.");
                } else {
                    messageLBL.setText("Ticket is already bought");
                }
                TicketSys.calcAllFees();

            }

        }
    }//GEN-LAST:event_buyBTNActionPerformed

    private void addFamMemberBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFamMemberBTNActionPerformed
        // TODO add your handling code here:
        if (famNameTF.getText().isEmpty() || famSurnameTF.getText().isEmpty() || famAgeTF.getText().isEmpty()) {
            messageLBL.setText("Please fill the blanks.");
        } else {
            ((Ticket) TicketSys.searchFlight(usernameTF.getText())).addFamilyMember(famNameTF.getText(),
                    famSurnameTF.getText(),
                    Integer.parseInt(famAgeTF.getText()));
            messageLBL.setText("Family member added");
        }

    }//GEN-LAST:event_addFamMemberBTNActionPerformed

    private void displayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBTNActionPerformed
        // TODO add your handling code here:
        if (TicketSys.getfArray().isEmpty()) {
            messageLBL.setText("There is no ticket to display.");
        } else {
            dispTA.setText(TicketSys.display());
        }
    }//GEN-LAST:event_displayBTNActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:

        if (TicketSys.getfArray().isEmpty()) {
            messageLBL.setText("Arraylist is empty!");
        } else {

            fillCB();
            st.setVisible(true);
        }


    }//GEN-LAST:event_searchActionPerformed

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        // TODO add your handling code here:
        famNameTF.setText("");
        famSurnameTF.setText("");
        famAgeTF.setText("");
        messageLBL.setText("");
    }//GEN-LAST:event_clearBTNActionPerformed

    private void clearAllBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllBTNActionPerformed
        // TODO add your handling code here:
        fromTF.setText("");
        toTF.setText("");
        depDayTF.setText("");
        depTimeTF.setText("");
        phoneTF.setText("");
        nameTF.setText("");
        surnameTF.setText("");
        ageTF.setText("");
        usernameTF.setText("");
        messageLBL.setText("");
        dispTA.setText("");
    }//GEN-LAST:event_clearAllBTNActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFamMemberBTN;
    private javax.swing.JButton addSpecialServices;
    private javax.swing.JTextField ageTF;
    private javax.swing.JTextField bookTF;
    private javax.swing.JRadioButton businessBTN;
    private javax.swing.JPanel businessPNL;
    private javax.swing.JButton buyBTN;
    private javax.swing.ButtonGroup classBG;
    private javax.swing.JButton clearAllBTN;
    private javax.swing.JButton clearBTN;
    private javax.swing.JTextField depDayTF;
    private javax.swing.JTextField depTimeTF;
    private javax.swing.JTextArea dispTA;
    private javax.swing.JButton displayBTN;
    private javax.swing.JTextField drinkTF;
    private javax.swing.JRadioButton economyBTN;
    private javax.swing.JPanel economyPNL;
    private javax.swing.JTextField famAgeTF;
    private javax.swing.JTextField famNameTF;
    private javax.swing.JTextField famSurnameTF;
    private javax.swing.JTextField foodTF;
    private javax.swing.JTextField fromTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField luggageTF;
    private javax.swing.JTextField luggage_bTF;
    private javax.swing.JPanel manageClassesPNL;
    private javax.swing.JLabel messageLBL;
    private javax.swing.JTextField movieTF;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTextField phoneTF;
    private javax.swing.JCheckBox purchaseMealCB;
    private javax.swing.JButton search;
    private javax.swing.JComboBox<String> seatTypeCMB;
    private javax.swing.JTextField surnameTF;
    private javax.swing.JPanel ticketInfoPNL;
    private javax.swing.JTextField toTF;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
