/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Has_A.SpecialServices;
import Is_A.*;
import Main_Sys.TicketSys;

/**
 *
 * @author User
 */
public class SpecialServicesFrame extends javax.swing.JFrame {

    /**
     * Creates new form SpecialServicesFrame
     */
    public SpecialServicesFrame() {
        initComponents();
        setTitle("Speacil Services Page");
        setLocationRelativeTo(null);
        setSize(600, 600);

        if (rentCarBTN.isSelected()) {
            rentCarPNL.setVisible(true);
            cityGuidePNL.setVisible(false);
            hotelReservationPNL.setVisible(false);
        } else if (cityGuideBTN.isSelected()) {
            rentCarPNL.setVisible(false);
            cityGuidePNL.setVisible(true);
            hotelReservationPNL.setVisible(false);
        } else if (hotelBTN.isSelected()) {
            rentCarPNL.setVisible(false);
            cityGuidePNL.setVisible(false);
            hotelReservationPNL.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        serviceGroup = new javax.swing.ButtonGroup();
        rentCarBTN = new javax.swing.JRadioButton();
        hotelBTN = new javax.swing.JRadioButton();
        cityGuideBTN = new javax.swing.JRadioButton();
        manageServices = new javax.swing.JPanel();
        hotelReservationPNL = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        hotelStarsCMB = new javax.swing.JComboBox<>();
        cityGuidePNL = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        languageTF = new javax.swing.JTextField();
        rentCarPNL = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        carModelCMB = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        serviceIDTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        durationTF = new javax.swing.JTextField();
        addServiceBTN = new javax.swing.JButton();
        displayBTN = new javax.swing.JButton();
        closeBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dispTA = new javax.swing.JTextArea();
        messageLBL = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        userNameTF = new javax.swing.JTextField();
        clearBTN = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        serviceGroup.add(rentCarBTN);
        rentCarBTN.setSelected(true);
        rentCarBTN.setText("Rent A Car");
        rentCarBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rentCarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentCarBTNActionPerformed(evt);
            }
        });
        getContentPane().add(rentCarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 110, 30));

        serviceGroup.add(hotelBTN);
        hotelBTN.setText("Hotel Reservation");
        hotelBTN.setActionCommand("");
        hotelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelBTNActionPerformed(evt);
            }
        });
        getContentPane().add(hotelBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        serviceGroup.add(cityGuideBTN);
        cityGuideBTN.setText("City Guide");
        cityGuideBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityGuideBTNActionPerformed(evt);
            }
        });
        getContentPane().add(cityGuideBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        manageServices.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hotelReservationPNL.setBorder(javax.swing.BorderFactory.createTitledBorder("Hotel Reservation"));
        hotelReservationPNL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Hotel Stars:");
        hotelReservationPNL.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 34, -1, -1));

        hotelStarsCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "4" }));
        hotelReservationPNL.add(hotelStarsCMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 31, -1, -1));

        manageServices.add(hotelReservationPNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 90));

        cityGuidePNL.setBorder(javax.swing.BorderFactory.createTitledBorder("City Guide"));
        cityGuidePNL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Language: ");
        cityGuidePNL.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        cityGuidePNL.add(languageTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 100, -1));

        manageServices.add(cityGuidePNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 80));

        rentCarPNL.setBorder(javax.swing.BorderFactory.createTitledBorder("Rent A Car"));
        rentCarPNL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Car Model: ");
        rentCarPNL.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 34, -1, -1));

        carModelCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rolls Royce", "Porsche", "Mercedes", "Bently", "Tesla" }));
        rentCarPNL.add(carModelCMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 31, 124, -1));

        manageServices.add(rentCarPNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 70));

        getContentPane().add(manageServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 290, 120));

        jLabel2.setText("Service ID: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, 20));
        getContentPane().add(serviceIDTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 40, -1));

        jLabel3.setText("Service Duration:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 20));
        getContentPane().add(durationTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 40, -1));

        addServiceBTN.setText("Add Service");
        addServiceBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addServiceBTNActionPerformed(evt);
            }
        });
        addServiceBTN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addServiceBTNKeyPressed(evt);
            }
        });
        getContentPane().add(addServiceBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        displayBTN.setText("Display Service");
        displayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBTNActionPerformed(evt);
            }
        });
        getContentPane().add(displayBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        closeBTN.setText("Close");
        closeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBTNActionPerformed(evt);
            }
        });
        getContentPane().add(closeBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        dispTA.setEditable(false);
        dispTA.setColumns(20);
        dispTA.setRows(5);
        jScrollPane1.setViewportView(dispTA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 290, 250));

        messageLBL.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(messageLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 360, 30));

        jLabel6.setText("Username:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
        getContentPane().add(userNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 80, -1));

        clearBTN.setText("Clear");
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });
        getContentPane().add(clearBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabel8.setText("(in days)");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rentCarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentCarBTNActionPerformed
        // TODO add your handling code here:
        rentCarPNL.setVisible(true);
        cityGuidePNL.setVisible(false);
        hotelReservationPNL.setVisible(false);
    }//GEN-LAST:event_rentCarBTNActionPerformed

    private void hotelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelBTNActionPerformed
        // TODO add your handling code here:
        rentCarPNL.setVisible(false);
        cityGuidePNL.setVisible(false);
        hotelReservationPNL.setVisible(true);
    }//GEN-LAST:event_hotelBTNActionPerformed

    private void cityGuideBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityGuideBTNActionPerformed
        // TODO add your handling code here:
        rentCarPNL.setVisible(false);
        cityGuidePNL.setVisible(true);
        hotelReservationPNL.setVisible(false);
    }//GEN-LAST:event_cityGuideBTNActionPerformed

    private void closeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBTNActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeBTNActionPerformed

    private void addServiceBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addServiceBTNActionPerformed
        // TODO add your handling code here:

        if (cityGuideBTN.isSelected()) {

            if (userNameTF.getText().isEmpty() || serviceIDTF.getText().isEmpty()
                    || durationTF.getText().isEmpty() || languageTF.getText().isEmpty()) {
                messageLBL.setText("Please fill the blanks.");
            } else {

                if ((Business) TicketSys.searchFlight(userNameTF.getText()) == null) {
                    messageLBL.setText("Username does not exist. You cannot add special service.");
                } else {
                    ((Business) TicketSys.searchFlight(userNameTF.getText())).addCityGuide(serviceIDTF.getText(),
                            durationTF.getText(), languageTF.getText());
                    ((Business) TicketSys.searchFlight(userNameTF.getText())).calcServiceFee();
                    messageLBL.setText("Service is added.");
                }

            }

        } else if (hotelBTN.isSelected()) {

            if (userNameTF.getText().isEmpty() || serviceIDTF.getText().isEmpty()
                    || durationTF.getText().isEmpty()) {
                messageLBL.setText("Please fill the blanks.");
            } else {

                if ((Business) TicketSys.searchFlight(userNameTF.getText()) == null) {
                    messageLBL.setText("Username does not exist. You cannot add special service.");
                } else {
                    ((Business) TicketSys.searchFlight(userNameTF.getText())).addHotelReservaion(serviceIDTF.getText(),
                            durationTF.getText(), (String) hotelStarsCMB.getSelectedItem());
                    ((Business) TicketSys.searchFlight(userNameTF.getText())).calcServiceFee();
                    messageLBL.setText("Service is added.");
                }
            }

        } else if (rentCarBTN.isSelected()) {

            if (userNameTF.getText().isEmpty() || serviceIDTF.getText().isEmpty()
                    || durationTF.getText().isEmpty()) {
                messageLBL.setText("Please fill the blanks.");
            } else {

                if ((Business) TicketSys.searchFlight(userNameTF.getText()) == null) {
                    messageLBL.setText("Username does not exist. You cannot add special service.");
                } else {
                    ((Business) TicketSys.searchFlight(userNameTF.getText())).addRentCar(serviceIDTF.getText(),
                            durationTF.getText(), (String) carModelCMB.getSelectedItem());
                    ((Business) TicketSys.searchFlight(userNameTF.getText())).calcServiceFee();
                    messageLBL.setText("Service is added.");
                }

            }

        }


    }//GEN-LAST:event_addServiceBTNActionPerformed

    private void displayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBTNActionPerformed
        // TODO add your handling code here:
        if ((Business) TicketSys.searchFlight(userNameTF.getText()) == null) {
            messageLBL.setText("The list is empty.");
        } else {
            dispTA.setText(((Business) TicketSys.searchFlight(userNameTF.getText())).toString());
        }
    }//GEN-LAST:event_displayBTNActionPerformed

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        // TODO add your handling code here:
        serviceIDTF.setText("");
        durationTF.setText("");
        dispTA.setText("");
        messageLBL.setText("");
    }//GEN-LAST:event_clearBTNActionPerformed

    private void addServiceBTNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addServiceBTNKeyPressed
        // TODO add your handling code here:
        
        if (cityGuideBTN.isSelected()) {

            if (userNameTF.getText().isEmpty() || serviceIDTF.getText().isEmpty()
                    || durationTF.getText().isEmpty() || languageTF.getText().isEmpty()) {
                messageLBL.setText("Please fill the blanks.");
            } else {

                if ((Business) TicketSys.searchFlight(userNameTF.getText()) == null) {
                    messageLBL.setText("Username does not exist. You cannot add special service.");
                } else {
                    ((Business) TicketSys.searchFlight(userNameTF.getText())).addCityGuide(serviceIDTF.getText(),
                            durationTF.getText(), languageTF.getText());
                    ((Business) TicketSys.searchFlight(userNameTF.getText())).calcServiceFee();
                    messageLBL.setText("Service is added.");
                }

            }

        } else if (hotelBTN.isSelected()) {

            if (userNameTF.getText().isEmpty() || serviceIDTF.getText().isEmpty()
                    || durationTF.getText().isEmpty()) {
                messageLBL.setText("Please fill the blanks.");
            } else {

                if ((Business) TicketSys.searchFlight(userNameTF.getText()) == null) {
                    messageLBL.setText("Username does not exist. You cannot add special service.");
                } else {
                    ((Business) TicketSys.searchFlight(userNameTF.getText())).addHotelReservaion(serviceIDTF.getText(),
                            durationTF.getText(), (String) hotelStarsCMB.getSelectedItem());
                    ((Business) TicketSys.searchFlight(userNameTF.getText())).calcServiceFee();
                    messageLBL.setText("Service is added.");
                }
            }

        } else if (rentCarBTN.isSelected()) {

            if (userNameTF.getText().isEmpty() || serviceIDTF.getText().isEmpty()
                    || durationTF.getText().isEmpty()) {
                messageLBL.setText("Please fill the blanks.");
            } else {

                if ((Business) TicketSys.searchFlight(userNameTF.getText()) == null) {
                    messageLBL.setText("Username does not exist. You cannot add special service.");
                } else {
                    ((Business) TicketSys.searchFlight(userNameTF.getText())).addRentCar(serviceIDTF.getText(),
                            durationTF.getText(), (String) carModelCMB.getSelectedItem());
                    ((Business) TicketSys.searchFlight(userNameTF.getText())).calcServiceFee();
                    messageLBL.setText("Service is added.");
                }

            }

        }


    }//GEN-LAST:event_addServiceBTNKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addServiceBTN;
    private javax.swing.JComboBox<String> carModelCMB;
    private javax.swing.JRadioButton cityGuideBTN;
    private javax.swing.JPanel cityGuidePNL;
    private javax.swing.JButton clearBTN;
    private javax.swing.JButton closeBTN;
    private javax.swing.JTextArea dispTA;
    private javax.swing.JButton displayBTN;
    private javax.swing.JTextField durationTF;
    private javax.swing.JRadioButton hotelBTN;
    private javax.swing.JPanel hotelReservationPNL;
    private javax.swing.JComboBox<String> hotelStarsCMB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField languageTF;
    private javax.swing.JPanel manageServices;
    private javax.swing.JLabel messageLBL;
    private javax.swing.JRadioButton rentCarBTN;
    private javax.swing.JPanel rentCarPNL;
    private javax.swing.ButtonGroup serviceGroup;
    private javax.swing.JTextField serviceIDTF;
    private javax.swing.JTextField userNameTF;
    // End of variables declaration//GEN-END:variables
}
